name: Deploy Platform (Bicep)

on:
  push:
    branches: [ "main" ]
    paths:
      - "infra/platform/**"
      - "bicepconfig.json"
      - ".github/workflows/platform.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "infra/platform/**"
      - "bicepconfig.json"

permissions:
  id-token: write
  contents: read

env:
  LOCATION: centralus
  RG_PLATFORM: rg-philguth-platform-dev
  DEPLOYMENT_NAME: platform-dev

jobs:
  whatif-or-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:  ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Ensure Resource Group
        run: |
          az group create -n "$RG_PLATFORM" -l "$LOCATION"

      - name: What-If (PR only)
        if: github.event_name == 'pull_request'
        run: |
          az deployment group what-if \
            -g "$RG_PLATFORM" \
            -n "$DEPLOYMENT_NAME" \
            -f infra/platform/main.bicep \
            -p infra/platform/dev.bicepparam

      - name: Deploy (push to main)
        if: github.event_name == 'push'
        run: |
          az deployment group create \
            -g "$RG_PLATFORM" \
            -n "$DEPLOYMENT_NAME" \
            -f infra/platform/main.bicep \
            -p infra/platform/dev.bicepparam
